services:
  backend:
    build:
      context: ./openmocha
      dockerfile: Dockerfile
    container_name: medusa-backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app:cached

